// client/src/view/login/index.vue
<template>
  <div class="login-container">
    <div class="item">
      <button @click="openDevtools">打开调试工具</button>
    </div>
    <div class="item">
      <webview
        name="zhihu"
        id="zhihu-login"
        src="https://www.zhihu.com/"
        useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
        style
      ></webview>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import _ from 'lodash'

export default defineComponent({
  name: 'dashboard',
  data() {
    return {}
  },
  methods: {
    openDevtools() {
      let webviewEle = document.querySelector('webview#zhihu-login')
      console.log('webviewEle => ', webviewEle)
      // @ts-ignore
      webviewEle?.openDevTools()
    },
  },
})
</script>

<style scoped>
.login-container {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
webview {
  display: inline-flex;
  width: 80vw;
  margin: 0 auto;
  height: 80vh;
}
</style>

// client/src/page/home/component/login/index.tsx
import { Button, message, Input, Form, Table, Modal, Tag, Card, Radio } from 'antd'

import { useState, useContext, useEffect } from 'react'
import * as Consts_Task_Config from '~/src/resource/const/task_config'
import * as Types_Task_Config from '~/src/resource/type/task_config'
import * as Consts from './resource/const/index'
import * as Types from './resource/type/index'

import './index.less'

export const Const_Storage_Key = 'login_msk'
const Const_Table_Column_Width = 100

export default () => {
  let [forceUpdate, setForceUpdate] = useState<number>(0)

  let [isModalShow, setIsModalShow] = useState<boolean>(false)
  let [isRecordListLoading, setIsRecordListLoading] = useState<boolean>(false)

  useEffect(() => {
    let asyncRunner = async () => {
      setIsRecordListLoading(true)
      setIsRecordListLoading(false)
    }
    asyncRunner()
  }, [forceUpdate])

  return (
    <div className="login">
      <div className="item">
        <Button
          onClick={() => {
            let webviewEle = document.querySelector('webview#zhihu-login')
            console.log('webviewEle => ', webviewEle)
            // @ts-ignore
            webviewEle.openDevTools()
          }}
          // @todo 待移除
        >
          打开调试面板
        </Button>
      </div>
      <div className="item">
        <webview
          id="zhihu-login"
          src="https://www.zhihu.com/"
          useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
        ></webview>
      </div>
    </div>
  )
}
